baseURL: "https://kalkayan.github.io"
title: Manish Sahani
paginate: 5
theme: kalkayan.paper

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: G-SXEKTQT09G

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Manish Sahani
  description: >
    Manish's protfolio and writings on experiences from working at adobe, 
    cncf and grorapid.
  author: Manish Sahani
  # author: ["Me", "You"] # multiple authors

  images: ["<link or path of image for opengraph, twitter-cards>"]

  ShowReadingTime: true
  ShowShareButtons: true
  comments: false
  defaultTheme: auto
  disableThemeToggle: false
  disableSpecial1stPost: false

  assets:
    favicon: "<link / abs url>"
    favicon16x16: "<link / abs url>"
    favicon32x32: "<link / abs url>"
    apple_touch_icon: "<link / abs url>"
    safari_pinned_tab: "<link / abs url>"

  label:
    text: "kalkayan"
    # icon: /kalkayan.png
    # iconHeight: 35

  # profile-mode
  profileMode:
    enabled: false # needs to be explicitly set
    title: Hi, I'm Manish Sahani
    # imageUrl: https://avatars0.githubusercontent.com/u/73003119?s=460&u=7fcec3d2195df48bac555e45ce1a27ef202b41bd&v=4
    # imageTitle: my image
    buttons:
      - name: Posts
        url: posts
      - name: Tags
        url: tags

  # home-info mode
  homeInfoParams:
    #Title: "How are you gonna be a revolutionary if you're such a traditionalist?"
    Title: "The Experiences to remember"
    Content: >
      **Hi, I'm Manish**, This website is the sum of my experiences. 
      So far, It includes great things I learned while making software, breaking software,
      and making software to break softwares. 

      

      I have interned at 
      [@adobe](https://www.adobe.com/), [@cncf (under kubernetes)](https://www.cncf.io/),
      and [@grorapid](https://www.grorapid.com/). Besides this, I'm an active contributor 
      to may live opensource projects - [Read more about me]().

  socialIcons:
    # - name: twitter
    #   url: "https://twitter.com/"
    # - name: stackoverflow
    #   url: "https://stackoverflow.com"
    - name: github
      url: "http://bit.ly/to-gh"
    - name: linkedin
      url: "http://bit.ly/to-lnkd"
    - name: email
      url: "mailto:rec.manish.sahani@gmail.com"

  analytics:
    google:
      SiteVerificationTag: "XYZabc"

menu:
  main:
    - identifier: about
      name: About
      url: /about/
      weight: 10
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 10
    - name: Posts
      url: /posts/
      weight: 10
    # - identifier: tags
    #   name: tags
    #   url: /tags/
    #   weight: 20
    # - identifier: terms
    #   name: terms
    #   url: /terms/
    #   weight: 20
    # - identifier: example
    #   name: example.org
    #   url: https://example.org
    #   weight: 30
